// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvOYSjSqdrEFfY-pzIRXcIW_IwtOskvEI',
    appId: '1:1080067213916:web:ddba8ccb9a980c0851b499',
    messagingSenderId: '1080067213916',
    projectId: 'sufaschool',
    authDomain: 'sufaschool.firebaseapp.com',
    storageBucket: 'sufaschool.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0dC01yEoYoTiLVcwYBZmOu3f84cFDVr0',
    appId: '1:1080067213916:android:98e4f3c5f889575a51b499',
    messagingSenderId: '1080067213916',
    projectId: 'sufaschool',
    storageBucket: 'sufaschool.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBO4-5btqJTKIYLVvfkJFRH4WQftylJHIo',
    appId: '1:1080067213916:ios:b6c4132729dece2551b499',
    messagingSenderId: '1080067213916',
    projectId: 'sufaschool',
    storageBucket: 'sufaschool.firebasestorage.app',
    iosBundleId: 'com.example.schoolApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBO4-5btqJTKIYLVvfkJFRH4WQftylJHIo',
    appId: '1:1080067213916:ios:b6c4132729dece2551b499',
    messagingSenderId: '1080067213916',
    projectId: 'sufaschool',
    storageBucket: 'sufaschool.firebasestorage.app',
    iosBundleId: 'com.example.schoolApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvOYSjSqdrEFfY-pzIRXcIW_IwtOskvEI',
    appId: '1:1080067213916:web:e9e828e0b227b1ac51b499',
    messagingSenderId: '1080067213916',
    projectId: 'sufaschool',
    authDomain: 'sufaschool.firebaseapp.com',
    storageBucket: 'sufaschool.firebasestorage.app',
  );
}
